/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ristorante;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import java.awt.event.*;
import javax.swing.*;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.regex.Pattern;


/**
 *
 * @author nicoa
 */
public class FRistorante extends javax.swing.JFrame {

    /**
     * Creates new form FRistorante
     */
    public FRistorante() {
        initComponents();
    }

    //connessione al db
    Connection con;
    PreparedStatement p;
    PreparedStatement p2;

    DefaultTableModel modello = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        check_carbo = new javax.swing.JCheckBox();
        check_pizza = new javax.swing.JCheckBox();
        check_ama = new javax.swing.JCheckBox();
        check_cala = new javax.swing.JCheckBox();
        check_bacc = new javax.swing.JCheckBox();
        tf_carbo = new javax.swing.JTextField();
        tf_ama = new javax.swing.JTextField();
        tf_pizza = new javax.swing.JTextField();
        tf_cala = new javax.swing.JTextField();
        tf_bacc = new javax.swing.JTextField();
        s_carbo = new javax.swing.JSpinner();
        s_pizza = new javax.swing.JSpinner();
        s_ama = new javax.swing.JSpinner();
        s_cala = new javax.swing.JSpinner();
        s_bacc = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_totale = new javax.swing.JTextField();
        t_pag = new javax.swing.JTextField();
        t_resto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Ristorante");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        check_carbo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        check_carbo.setText("Carbonara");
        check_carbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_carboActionPerformed(evt);
            }
        });

        check_pizza.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        check_pizza.setText("Pizza");
        check_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_pizzaActionPerformed(evt);
            }
        });

        check_ama.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        check_ama.setText("Amatriciana");
        check_ama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_amaActionPerformed(evt);
            }
        });

        check_cala.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        check_cala.setText("Calamari fritti");
        check_cala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_calaActionPerformed(evt);
            }
        });

        check_bacc.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        check_bacc.setText("Baccalà");
        check_bacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_baccActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/sebastian-coman-photography-mVwQrsnnbHg-unsplash.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/ivan-torres-MQUqbmszGGM-unsplash.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/krista-stucchio-2CZ0Zpuj-gU-unsplash.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/melissa-walker-horn-7QVsqKJapQg-unsplash.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/david-b-townsend-AnC569NdAJc-unsplash.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_pizza)
                            .addComponent(tf_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_carbo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_carbo))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(s_carbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(s_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel7)
                                .addGap(0, 6, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(check_cala)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tf_bacc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(s_cala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(check_ama)
                                    .addComponent(tf_ama, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(s_ama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tf_cala, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(s_bacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(check_bacc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(check_carbo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_carbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_carbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check_pizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(check_ama)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_ama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_ama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check_cala)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_bacc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_cala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check_bacc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_cala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_bacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Prezzo", "Quantità", "Totale"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Totale");

        jLabel3.setText("Pagamento");

        jLabel4.setText("Resto");

        jButton2.setText("Stampa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Aggiungi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_resto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_totale, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(382, 382, 382))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_totale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(t_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_resto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        b.setColumns(20);
        b.setRows(5);
        jScrollPane2.setViewportView(b);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(677, 677, 677))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void check_carboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_carboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_carboActionPerformed

    private void check_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_pizzaActionPerformed

    private void check_amaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_amaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_amaActionPerformed

    private void check_calaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_calaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_calaActionPerformed

    private void check_baccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_baccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_baccActionPerformed

    
    
    
    
    //Stampiampo la ricevuta
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //se non viene inserito l'importo con cui si desidera pagare stampa un messaggio
        if (t_pag.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Inserisci l'importo con cui pagare prima di procedere! ");

        }

        int totale_c = Integer.parseInt(t_totale.getText());
        int pagamento = Integer.parseInt(t_pag.getText());
        int resto = pagamento - totale_c;

        t_resto.setText(String.valueOf(resto));

        //Creo la ricevuta
        try {
            b.setText("                       Ristorante\n");
            b.setText(b.getText() + "                       Via Martin Luther King\n");
            b.setText(b.getText() + "                       55\n");
            b.setText(b.getText() + "                       Milano\n");
            b.setText(b.getText() + "                       +39 3451234567\n");
            b.setText(b.getText() + " ----------------------------------------------------------------------------------\n");

            b.setText(b.getText() + "  Nome \tPrezzo \tQuantità" + "\n");

            b.setText(b.getText() + " ----------------------------------------------------------------------------------\n");

            //Stampo gli elementi dell'ordine all'interno dell'aria di testo
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String nome = modello.getValueAt(i, 0).toString();
                String Prezzo = modello.getValueAt(i, 1).toString();
                String Quantità = modello.getValueAt(i, 2).toString();

                b.setText(b.getText() + " " + nome + "\t" + Prezzo + "\t" + Quantità + "\n");

            }

            b.setText(b.getText() + " ----------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "Totale : " + t_totale.getText() + "\n");
            b.setText(b.getText() + "Pagamento : " + t_pag.getText() + "\n");
            b.setText(b.getText() + "Resto : " + resto + "\n");
            b.setText(b.getText() + " ----------------------------------------------------------------------------------\n");
            b.setText(b.getText() + " Grazie mille per l'acquisto! " + "\n");

            //Apri il comando di stampa di windows
            b.print();

        } catch (Exception e) {

            System.out.println(e);
        }

        vendite();
    }//GEN-LAST:event_jButton2ActionPerformed

    //funzioni per il database
    public void vendite() {

        String totale_complessivo = t_totale.getText();
        String pagamento = t_pag.getText();
        String rest = t_resto.getText();

        int id = 0;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/ristorante", "root", "");

            String Query = "insert into vendite(totale_complessivo, pagamento, resto)values(?,?,?)";

            p = con.prepareStatement(Query, Statement.RETURN_GENERATED_KEYS);

            p.setString(1, totale_complessivo);
            p.setString(2, pagamento);
            p.setString(3, rest);
            p.executeUpdate();

            ResultSet creachiave = p.getGeneratedKeys();

            if (creachiave.next()) {

                id = creachiave.getInt(1);
            }

            int righe = jTable1.getRowCount();
            String query = "insert into prodotti(fattura_id, tipoProdotto, prezzo, quantità, totale) value(?,?,?,?,?)";

            p2 = con.prepareStatement(query);
            String tipoProdotto = "";
            int prezzo = 0;
            int quantità = 0;
            int totale = 0;

            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                tipoProdotto = (String) jTable1.getValueAt(i, 0);
                prezzo = (int) jTable1.getValueAt(i, 1);
                quantità = (int) jTable1.getValueAt(i, 2);
                totale = (int) jTable1.getValueAt(i, 3);

                p2.setInt(1, id);
                p2.setString(2, tipoProdotto);
                p2.setInt(3, prezzo);
                p2.setInt(4, quantità);
                p2.setInt(5, totale);
                p2.executeUpdate();
            }

            p.addBatch();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FRistorante.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FRistorante.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    //bottone che confermerà i dati e farà la sommma degli elementi da acquistare
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InserisciNumeri();

        int somma = 0;

        if (check_carbo.isSelected() || check_pizza.isSelected() || check_ama.isSelected() || check_cala.isSelected() || check_bacc.isSelected()) {
            //se il nostro elemento è stato selezionato prendiamo in input il prezzo e la quantità
            if (check_carbo.isSelected()) {

                if (!tf_carbo.getText().isEmpty()) {
                    String Carbo = check_carbo.getText();
                    int prezzo = Integer.parseInt(tf_carbo.getText());
                    int quantità = Integer.parseInt(s_carbo.getValue().toString());   //Prendiamo il valore della quantità dallo spinner
                    int totale = prezzo * quantità;  //calcoliamo il totale

                    //Aggiungiamo ad ogni riga i dati presi in imput
                    modello = (DefaultTableModel) jTable1.getModel();

                    modello.addRow(new Object[]{
                        Carbo, prezzo, quantità, totale
                    });

                } else {
                    JOptionPane.showMessageDialog(null, "Inserisci il prezzo");
                }

            }

            //se il nostro elemento è stato selezionato prendiamo in input il prezzo e la quantità
            if (check_pizza.isSelected()) {

                if (!tf_pizza.getText().isEmpty()) {
                    String pizza = check_pizza.getText();
                    int prezzo = Integer.parseInt(tf_pizza.getText());
                    int quantità = Integer.parseInt(s_pizza.getValue().toString());   //Prendiamo il valore della quantità dallo spinner
                    int totale = prezzo * quantità;  //calcoliamo il totale

                    //Aggiungiamo ad ogni riga i dati presi in imput
                    modello = (DefaultTableModel) jTable1.getModel();

                    modello.addRow(new Object[]{
                        pizza, prezzo, quantità, totale
                    });

                } else {
                    JOptionPane.showMessageDialog(null, "Inserisci il prezzo");
                }
            }

            //se il nostro elemento è stato selezionato prendiamo in input il prezzo e la quantità
            if (check_ama.isSelected()) {

                if (!tf_ama.getText().isEmpty()) {
                    String ama = check_ama.getText();
                    int prezzo = Integer.parseInt(tf_ama.getText());
                    int quantità = Integer.parseInt(s_ama.getValue().toString());   //Prendiamo il valore della quantità dallo spinner
                    int totale = prezzo * quantità;  //calcoliamo il totale

                    //Aggiungiamo ad ogni riga i dati presi in imput
                    modello = (DefaultTableModel) jTable1.getModel();

                    modello.addRow(new Object[]{
                        ama, prezzo, quantità, totale
                    });

                } else {
                    JOptionPane.showMessageDialog(null, "Inserisci il prezzo");
                }
            }

            //se il nostro elemento è stato selezionato prendiamo in input il prezzo e la quantità
            if (check_cala.isSelected()) {

                if (!tf_cala.getText().isEmpty()) {
                    String cala = check_cala.getText();
                    int prezzo = Integer.parseInt(tf_cala.getText());
                    int quantità = Integer.parseInt(s_cala.getValue().toString());   //Prendiamo il valore della quantità dallo spinner
                    int totale = prezzo * quantità;  //calcoliamo il totale

                    //Aggiungiamo ad ogni riga i dati presi in imput
                    modello = (DefaultTableModel) jTable1.getModel();

                    modello.addRow(new Object[]{
                        cala, prezzo, quantità, totale
                    });

                } else {
                    JOptionPane.showMessageDialog(null, "Inserisci il prezzo");
                }

            }

            //se il nostro elemento è stato selezionato prendiamo in input il prezzo e la quantità
            if (check_bacc.isSelected()) {

                if (!tf_bacc.getText().isEmpty()) {
                    String bacc = check_bacc.getText();
                    int prezzo = Integer.parseInt(tf_bacc.getText());
                    int quantità = Integer.parseInt(s_bacc.getValue().toString());   //Prendiamo il valore della quantità dallo spinner
                    int totale = prezzo * quantità;  //calcoliamo il totale

                    //Aggiungiamo ad ogni riga i dati presi in imput
                    modello = (DefaultTableModel) jTable1.getModel();

                    modello.addRow(new Object[]{
                        bacc, prezzo, quantità, totale
                    });

                } else {
                    JOptionPane.showMessageDialog(null, "Inserisci il prezzo");
                }

            }

            //calcoliamo il totale complessivo che ci consentirà di fare lo scontrino sommando il totale di ogni istanza della tabella
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                somma = somma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());   //per ogni istanza della tabella aggiunge il totale alla variabile somma

            }

            //stampiamo il totale
            t_totale.setText(Integer.toString(somma));

            JOptionPane.showMessageDialog(null, "Ordine effettuato! ");
        } else {
            JOptionPane.showMessageDialog(null, "Seleziona almeno un prodotto");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        setTextNull();

        modello.setRowCount(0);


    }//GEN-LAST:event_jButton3ActionPerformed

    public void setTextNull(){
        tf_carbo.setText(null);
        tf_pizza.setText(null);
        tf_ama.setText(null);
        tf_cala.setText(null);
        tf_bacc.setText(null);
        t_totale.setText(null);
        t_pag.setText(null);
        t_resto.setText(null);
        
        b.setText(null);

        s_carbo.setValue(0);
        s_pizza.setValue(0);
        s_ama.setValue(0);
        s_cala.setValue(0);
        s_bacc.setValue(0);

        check_carbo.setSelected(false);
        check_pizza.setSelected(false);
        check_ama.setSelected(false);
        check_cala.setSelected(false);
        check_bacc.setSelected(false);
        
        
    }
    
    
    public void InserisciNumeri (){
        String carbo = tf_carbo.getText();
        String pizza = tf_pizza.getText();
        String ama = tf_ama.getText();
        String cala = tf_cala.getText();
        String bacc = tf_bacc.getText();
        
        String pag = t_pag.getText();
        
        if(!contieneSoloNumeri(carbo,pizza,ama,cala,bacc,pag)){
            JOptionPane.showMessageDialog(null,"Inserisci numeri");
        }
        
        
        
        
    }
    
    
    
    // Implementiamo un metodo che verifichi se la stringa numero ha solo numeri
    public static boolean contieneSoloNumeri(String carbo, String pizza, String ama, String cala, String bacc, String pag) {
        Pattern formato = Pattern.compile("\\d+");
        return formato.matcher(carbo).matches();
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRistorante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRistorante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRistorante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRistorante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRistorante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea b;
    private javax.swing.JCheckBox check_ama;
    private javax.swing.JCheckBox check_bacc;
    private javax.swing.JCheckBox check_cala;
    private javax.swing.JCheckBox check_carbo;
    private javax.swing.JCheckBox check_pizza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner s_ama;
    private javax.swing.JSpinner s_bacc;
    private javax.swing.JSpinner s_cala;
    private javax.swing.JSpinner s_carbo;
    private javax.swing.JSpinner s_pizza;
    private javax.swing.JTextField t_pag;
    private javax.swing.JTextField t_resto;
    private javax.swing.JTextField t_totale;
    private javax.swing.JTextField tf_ama;
    private javax.swing.JTextField tf_bacc;
    private javax.swing.JTextField tf_cala;
    private javax.swing.JTextField tf_carbo;
    private javax.swing.JTextField tf_pizza;
    // End of variables declaration//GEN-END:variables
}
